name: Docker Image CI

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Build the Docker image
        run: cd .devcontainer && docker build . --file Dockerfile --tag aws-terraform-dev-container:${{ github.run_id }}
