name: Hygiene

on:
  push:

permissions:
  contents: read

jobs:
  code-hygiene:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          make tfswitch/install tfswitch/run
          make tflint/install tfsec/install checkov/install terrascan/install

      # We are ignoring pre-commit checks on purpose in order for demonstrating purposes and progress with other jobs
      # You shouldn't ignore your pre-commit checks and their respective warnings, please remediate them accordingly.
      - name: Install pre-commit hooks and execute rules
        run: pre-commit run --all-files || true

  doc-hygiene:
    needs: code-hygiene
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build documentation
        run: make doc/build

      - name: Check documentation status
        run: git diff --exit-code # exit 1 if there's a difference between what was pushed with what was produced by doc/build.
